[tools]
"aqua:denoland/deno" = "latest"
"aqua:pnpm" = "latest"
go = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
rust = "latest"
"cargo:xremap" = { version = "latest", feature = "gnome"}

[settings]
experimental = true
