[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:denoland/deno" = "latest"
"aqua:pnpm" = "latest"
go = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:turbo" = "latest"
rust = "latest"
"aqua:pulumi/pulumi" = "latest"
"aqua:pulumi/esc" = "latest"
"aqua:aws-cli" = "latest"
"aqua:oven-sh/bun" = "latest"
"aqua:go-task/task" = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@ariga/atlas" = "0.37.0"
"npm:vercel" = "48.1.6"
"aqua:evilmartians/lefthook" = "1.13.4"

[settings]
experimental = true
pin = true
