[tools]
"aqua:denoland/deno" = "latest"
"aqua:pnpm" = "latest"
go = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:turbo" = "latest"
rust = "latest"

[settings]
experimental = true
